package org.bongz.enums;

public enum ConfigProperties {
	URL,
	OVERRIDEREPORTS,
	PASSEDSTEPSCREENSHOT,
	FAILEDSTEPSCREENSHOT,
	SKIPPEDSTEPSCREENSHOT,
	RETRYFAILEDTESTS,
	SENDRESULTSTOELK,
	SELENIUMGRIDURL,
	ELASTICURL,
	SENDEMAILREPORT,
	RUNMODE,
	BROWSER
}
